apiVersion: v1
kind: Service
metadata:
  name: deployment-test-app
  labels:
    app: deployment-test-app
spec:
  selector:
    app: deployment-test-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
